fmdbt:
  target: dev
  outputs:
    dev:
      type: fabric
      driver: "ODBC Driver 18 for SQL Server" # (The ODBC Driver installed on your system)
      server: e7aqlsk7kkuupa7rx3abj5wwcm-emb274pgjxyu3k6q55xtame6nu.datawarehouse.pbidedicated.windows.net
      port: 1433
      database: dbtdemodev
      schema: raw
      authentication: CLI
      threads: 2

    prod:
      type: fabric
      driver: "ODBC Driver 18 for SQL Server" # (The ODBC Driver installed on your system)
      server: e7aqlsk7kkuupa7rx3abj5wwcm-emb274pgjxyu3k6q55xtame6nu.datawarehouse.pbidedicated.windows.net
      port: 1433
      database: dbtdemoprod
      schema: raw
      authentication: CLI
      threads: 2
